### ISSUE TITLE
Constant Crash on Windows 8.1

### ISSUE THREAD

**Issue by Evan-Sa** [felipedaragon/sandcat#2]
Sandcat becomes unresponsive even when there is not intensive processes going on such as opening a web page.

**Comment by felipedaragon** [comment]
Hello! Thanks for the report. Is the Windows 8.1 you are using 32 or 64 bit?

**Comment by Evan-Sa** [comment]
Hello thanks getting back to me. The machine is 64 bit version of 8.1
On Jul 16, 2015 11:53 AM, "Felipe Daragon" <notifications@github.com> wrote:
>
> Hello! Thanks for the report. Is the Windows 8.1 you are using 32 or 64
bit?

**Comment by Evan-Sa** [comment]
Any progress @felipedaragon  I have not been able to resolve  the issue. Do you typically run sandcat on 32 bit machines?

**Comment by felipedaragon** [comment]
Hello again! Yes, 32. This is likely arising from some incompatibility between the 32-bit CEF (Chromium) library and the 64-bit environment you are in.

**Comment by Evan-Sa** [comment]
That's unfortunate besides creating a 32 bit VM or installing 32 bit
machine is there any way I can emulate a 32 bit environment?

**Comment by felipedaragon** [comment]
I expect to produce a native 64-bit release soon.

**Comment by felipedaragon** [comment]
Hi Evan-Sa! There is now a 64-bit beta release (second link at https://github.com/felipedaragon/sandcat#download) Can you confirm if the issue you reported is gone with this release?

**Comment by Evan-Sa** [comment]
Hello Felipe,

Thank you for the reply, unfortunately this issue is still present. I tested on both a windows 8.1 and windows10 64 bit computers and had the same issue of the browser becoming unresponsive & crashing.

**Comment by felipedaragon** [comment]
Could you send more details on how I can try to reproduce this issue to my email?

**Comment by felipedaragon** [comment]
Does it happens when visiting some specific URL?

**Comment by maninoipar** [comment]
Hey, there. I have the same issue as described above, you can reproduce it just by making use of the browser and opening any one of the tools (the injector is the one that crashes on me the most).

Do you want me to make some specific tests or give you some special log? I'm on Windows 10 x64.

**Comment by felipedaragon** [comment]
@maninoipar @Evan-Sa can you check the latest release [sandcat-5.2b2-win64.exe](https://syhunt.websiteseguro.com/pub/downloads/sandcat-5.2b2-win64.exe) ?

**Comment by maninoipar** [comment]
@felipedaragon It may be worse than before. I tried many times with different methods and URLs and it crashes each time.

**Comment by Evan-Sa** [comment]
@felipedaragon I can conur I tried on a win 10 x 64 bit and saw it crash on different urls each time.

**Comment by felipedaragon** [comment]
Hello @Evan-Sa and @maninoipar, I believe I managed to reproduce and fix the issue you reported. Please let me know how version 5.3 goes. Download it from: https://github.com/felipedaragon/sandcat#download
